### ISSUE TITLE
nativesdk-liblldb contains reference to TMPDIR [buildpaths]

### ISSUE THREAD

**Issue by sapiippo** [kraj/meta-clang#1022]
Build of nativesdk-clang from meta-clang[master] against poky[styhead] fails with QA error:

```
ERROR: nativesdk-clang-19.1.2-r0 do_package_qa: QA Issue: File /usr/local/oe-sdk-hardcoded-buildpath/sysroots/x86_64-pokysdk-linux/usr/lib/liblldb.so.19.1.2 in package nativesdk-liblldb contains reference to TMPDIR [buildpaths]         
ERROR: nativesdk-clang-19.1.2-r0 do_package_qa: Fatal QA errors were found, failing task.
```

**Comment by lms-jk** [comment]
Also affected by this issue.

**Comment by lms-jk** [comment]
Adding `LLVM_APPEND_VC_REV=OFF` to `EXTRA_OECMAKE:append:class-nativesdk` in `clang_git.bb` (from https://github.com/kraj/meta-clang/commit/a5ebfbeaec07929844bc902fb386b229e360bde8 ) did not help.

**Comment by lms-jk** [comment]
liblldb contains/path/to/TMPDIR/work/x86_64-nativesdk-oesdk-linux/nativesdk-clang/19.1.0/recipe-sysroot-native/usr/bin/python3-native/python3

**Comment by lms-jk** [comment]
Setting `LLDB_PYTHON_EXE_RELATIVE_PATH` to `${PYTHON_PN}` fixes the build. However, I am not quite sure if this breaks the Python capabilities of LLDB.
