### ISSUE TITLE
FEATURE REQUEST: Clang-tools-extra

### ISSUE THREAD

**Issue by tomasz3dk** [kraj/meta-clang#103]
Is any chance to include clang-tools-extra (or only clang-tidy) into layer?

**Comment by kraj** [comment]
Yes sure that will be a good  addition  but I dont know when I can get to that, but if someone beats me tto the patch that will be awesome.

**Comment by tomasz3dk** [comment]
Well. I can try. Can you provide some hints from which recipes should i start looking at?

**Comment by tomasz3dk** [comment]
I've tested latest commit on master branch and it seems that clang-tools-extra are already included. Did you provide some patch or maybe changing revision do the job or maybe I missed something ;)?

**Comment by kraj** [comment]
build has been overhauled recently to use monorepo, which has enabled building additional tools however, I have not tested extra tools. if it works for you then close this ticket.

**Comment by tomasz3dk** [comment]
Ok. I'm closing it.
