### ISSUE TITLE
qa warnning: already stripped

### ISSUE THREAD

**Issue by walkthetalk** [kraj/meta-clang#11]
WARNING: clang-native-3.8.0+gitAUTOINC+27c964e2ae_b98cd9d6a3-r0 do_populate_sysroot: File '/mnt/optimus/build/tmp/sysroots/x86_64-linux/usr/bin/llc' from clang-native was already stripped, this will prevent future debugging!

**Comment by kraj** [comment]
This is due to we choosing to strip this during clang make itself. So we need to ignore this qa check. Otherwise size gets out of control

**Comment by walkthetalk** [comment]
If so, I think we should add INSAN_SKIP in bb file

**Comment by walkthetalk** [comment]
INSANE_SKIP_${PN} += "already-stripped"
INSANE_SKIP_${PN}-native += "already-stripped"
INSANE_SKIP_nativesdk-${PN} += "already-stripped"

the first line can work, but I don't know what is the right code for native and nativesdk.

**Comment by kraj** [comment]
First 2 are ok. Third one needs to usr target arch. Look into clang.bbclass for sample

**Comment by walkthetalk** [comment]
pull request #15 insane skip 'already-stripped'

**Comment by kraj** [comment]
should be fixed now
