### ISSUE TITLE
FEATURE: Support building clang-tools

### ISSUE THREAD

**Issue by edtanous** [kraj/meta-clang#113]
clang-tidy and clang-format (as well as other tools) are useful utilities in the clang-tools-extras package.  It would be helpful if this meta layer supported compiling those as part of its build.

I'm happy to start looking at how it could be done, and send a PR if I get far, but any pointers on where to start would be appreciated.

https://clang.llvm.org/extra/index.html

**Comment by tomasz3dk** [comment]
Those tools are already included in master branch since master branch is using clang in 8 version.

**Comment by edtanous** [comment]
So they are.  I was running an older branch.  Sorry for the noise.
