### ISSUE TITLE
nativesdk-clang package error

### ISSUE THREAD

**Issue by walkthetalk** [kraj/meta-clang#12]
ERROR: nativesdk-clang-3.8.0+gitAUTOINC+27c964e2ae_b98cd9d6a3-r0 do_package: QA Issue: nativesdk-clang: Files/directories were installed but not shipped in any package:
  /opt/optimus/2.0+snapshot/sysroots/x86_64-optimussdk-linux/usr/share/llvm

nativesdk-clang-3.8.0+gitAUTOINC+27c964e2ae_b98cd9d6a3-r0 do_package_qa: QA Issue: -dev package contains non-symlink .so: nativesdk-clang-dev path 'work/x86_64-nativesdk-optimussdk-linux/nativesdk-clang/3.8.0+gitAUTOINC+27c964e2ae_b98cd9d6a3-r0/packages-split/nativesdk-clang-dev/opt/optimus/2.0+snapshot/sysroots/x86_64-optimussdk-linux/usr/lib/libLTO.so' [dev-elf]

**Comment by walkthetalk** [comment]
maybe we can use archlinux as reference, split the llvm from clang.

**Comment by kraj** [comment]
Fixed by 39bcfb9

**Comment by walkthetalk** [comment]
this commit will not fix 'dev-elf' error.
