### ISSUE TITLE
systemd 241: fails to build

### ISSUE THREAD

**Issue by MastaG** [kraj/meta-clang#122]
Hi there @kraj 

After I updated OE and meta-clang, systemd now fails to build?

| FAILED: src/shared/5afaae1@@systemd-shared-241@sta/json.c.o
| arm-oe-linux-gnueabi-clang -mthumb -mfpu=neon-vfpv4 -mfloat-abi=hard -mcpu=cortex-a15 --rtlib=compiler-rt --stdlib=libc++ -mlittle-endian -Wno-error=unused-command-line-argument -Qunused-arguments --sysroot=/media/data/home/mastag/odroid-oe-core/build/tmp/work/cortexa15t2hf-neon-vfpv4-oe-linux-gnueabi/systemd/1_241+AUTOINC+c1f8ff8d0d-r0/recipe-sysroot -Isrc/shared/5afaae1@@systemd-shared-241@sta -Isrc/shared -I../git/src/shared -Isrc/basic -I../git/src/basic -Isrc/systemd -I../git/src/systemd -Isrc/journal -I../git/src/journal -Isrc/journal-remote -I../git/src/journal-remote -Isrc/nspawn -I../git/src/nspawn -Isrc/resolve -I../git/src/resolve -Isrc/timesync -I../git/src/timesync -I../git/src/time-wait-sync -Isrc/login -I../git/src/login -Isrc/udev -I../git/src/udev -Isrc/libudev -I../git/src/libudev -Isrc/core -I../git/src/core -I../git/src/libsystemd/sd-bus -I../git/src/libsystemd/sd-device -I../git/src/libsystemd/sd-event -I../git/src/libsystemd/sd-hwdb -I../git/src/libsystemd/sd-id128 -I../git/src/libsystemd/sd-netlink -I../git/src/libsystemd/sd-network -I../git/src/libsystemd/sd-resolve -Isrc/libsystemd-network -I../git/src/libsystemd-network -I. -I../git/ -I/media/data/home/mastag/odroid-oe-core/build/tmp/work/cortexa15t2hf-neon-vfpv4-oe-linux-gnueabi/systemd/1_241+AUTOINC+c1f8ff8d0d-r0/recipe-sysroot/usr/include/libmount -I/media/data/home/mastag/odroid-oe-core/build/tmp/work/cortexa15t2hf-neon-vfpv4-oe-linux-gnueabi/systemd/1_241+AUTOINC+c1f8ff8d0d-r0/recipe-sysroot/usr/include/blkid -I/media/data/home/mastag/odroid-oe-core/build/tmp/work/cortexa15t2hf-neon-vfpv4-oe-linux-gnueabi/systemd/1_241+AUTOINC+c1f8ff8d0d-r0/recipe-sysroot/usr/include/uuid -Xclang -fcolor-diagnostics -pipe -D_FILE_OFFSET_BITS=64 -Wextra -Werror=undef -Wmissing-include-dirs -Wold-style-definition -Wpointer-arith -Winit-self -Wfloat-equal -Werror=missing-prototypes -Werror=implicit-function-declaration -Werror=missing-declarations -Werror=return-type -Werror=incompatible-pointer-types -Werror=format=2 -Wstrict-prototypes -Wredundant-decls -Wmissing-noreturn -Wshadow -Wendif-labels -Wstrict-aliasing=2 -Wwrite-strings -Werror=overflow -Werror=shift-count-overflow -Wdate-time -Wnested-externs -Wno-unused-parameter -Wno-missing-field-initializers -Wno-unused-result -Wno-error=nonnull -ffast-math -fno-common -fdiagnostics-show-option -fno-strict-aliasing -fvisibility=hidden -fstack-protector -fstack-protector-strong --param=ssp-buffer-size=4 -Wno-typedef-redefinition -Wno-gnu-variable-sized-type-not-at-end -ffunction-sections -fdata-sections -Werror=shadow -include config.h -mthumb -mfpu=neon-vfpv4 -mfloat-abi=hard -mcpu=cortex-a15 --rtlib=compiler-rt --stdlib=libc++ -mlittle-endian -Wno-error=unused-command-line-argument -Qunused-arguments --sysroot=/media/data/home/mastag/odroid-oe-core/build/tmp/work/cortexa15t2hf-neon-vfpv4-oe-linux-gnueabi/systemd/1_241+AUTOINC+c1f8ff8d0d-r0/recipe-sysroot -O2 -g -feliminate-unused-debug-types -fmacro-prefix-map=/media/data/home/mastag/odroid-oe-core/build/tmp/work/cortexa15t2hf-neon-vfpv4-oe-linux-gnueabi/systemd/1_241+AUTOINC+c1f8ff8d0d-r0=/usr/src/debug/systemd/1_241+AUTOINC+c1f8ff8d0d-r0 -fdebug-prefix-map=/media/data/home/mastag/odroid-oe-core/build/tmp/work/cortexa15t2hf-neon-vfpv4-oe-linux-gnueabi/systemd/1_241+AUTOINC+c1f8ff8d0d-r0=/usr/src/debug/systemd/1_241+AUTOINC+c1f8ff8d0d-r0 -fdebug-prefix-map=/media/data/home/mastag/odroid-oe-core/build/tmp/work/cortexa15t2hf-neon-vfpv4-oe-linux-gnueabi/systemd/1_241+AUTOINC+c1f8ff8d0d-r0/recipe-sysroot= -fdebug-prefix-map=/media/data/home/mastag/odroid-oe-core/build/tmp/work/cortexa15t2hf-neon-vfpv4-oe-linux-gnueabi/systemd/1_241+AUTOINC+c1f8ff8d0d-r0/recipe-sysroot-native= -fPIC -pthread -fvisibility=default -MD -MQ 'src/shared/5afaae1@@systemd-shared-241@sta/json.c.o' -MF 'src/shared/5afaae1@@systemd-shared-241@sta/json.c.o.d' -o 'src/shared/5afaae1@@systemd-shared-241@sta/json.c.o' -c ../git/src/shared/json.c
| In file included from ../git/src/shared/json.c:18:
| In file included from ../git/src/shared/json-internal.h:5:
| In file included from ../git/src/shared/json.h:10:
| In file included from ../git/src/basic/util.h:29:
| ../git/src/basic/missing_stdlib.h:17:9: warning: 'strndupa' macro redefined [-Wmacro-redefined]
| #define strndupa(s, n) \
|         ^
| /media/data/home/mastag/odroid-oe-core/build/tmp/work/cortexa15t2hf-neon-vfpv4-oe-linux-gnueabi/systemd/1_241+AUTOINC+c1f8ff8d0d-r0/recipe-sysroot/usr/include/string.h:190:10: note: previous definition is here
| # define strndupa(s, n)                                                       \
|          ^
| In file included from ../git/src/shared/json.c:18:
| ../git/src/shared/json-internal.h:43:11: error: static_assert expression is not an integral constant expression
| assert_cc((uintptr_t) _JSON_VARIANT_MAGIC_MAX < 4096U);
| ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| ../git/src/basic/macro.h:344:23: note: expanded from macro 'assert_cc'
|         static_assert(expr, #expr);
|                       ^~~~
| ../git/src/shared/json-internal.h:43:11: note: cast that performs the conversions of a reinterpret_cast is not allowed in a constant expression
| 1 warning and 1 error generated.

I couldn't find a fix for this easily.

**Comment by kraj** [comment]
this should already be fixed with latest OE-core@master if not please reopen.
