### ISSUE TITLE
nativesdk-clang package error (dev-elf)

### ISSUE THREAD

**Issue by walkthetalk** [kraj/meta-clang#14]
nativesdk-clang-3.8.0+gitAUTOINC+27c964e2ae_b98cd9d6a3-r0 do_package_qa: QA Issue: -dev package contains non-symlink .so: nativesdk-clang-dev path 'work/x86_64-nativesdk-optimussdk-linux/nativesdk-clang/3.8.0+gitAUTOINC+27c964e2ae_b98cd9d6a3-r0/packages-split/nativesdk-clang-dev/opt/optimus/2.0+snapshot/sysroots/x86_64-optimussdk-linux/usr/lib/libLTO.so' [dev-elf]

**Comment by walkthetalk** [comment]
FILES_${PN}_append_class-nativesdk = "\
  ${libdir_native}/libLTO.so \
"

I don't know if it is the right style.

**Comment by kraj** [comment]
This is right. But you need a insane skip

**Comment by walkthetalk** [comment]
pull request #15 insane skip 'dev-elf'

**Comment by kraj** [comment]
should be fixed
