### ISSUE TITLE
Building with poky thud fails

### ISSUE THREAD

**Issue by russell-islam** [kraj/meta-clang#197]
Loading cache: 100% |#########################################################################################| Time: 0:00:00
Loaded 3512 entries from dependency cache.
ERROR: No recipes available for:
  /home/xxx/sources/poky/../meta-clang/recipes-core/musl/musl_%.bbappend
Summary: There were 2 WARNING messages shown.
Summary: There was 1 ERROR message shown, returning a non-zero exit code.

**Comment by kraj** [comment]
what branch of poky are you using?  it is `thud` too.

**Comment by russell-islam** [comment]
yes

**Comment by kraj** [comment]
Do you have musl recipe inside poky/meta/recipes-core/

**Comment by russell-islam** [comment]
Yes. 
./sources/meta-clang/recipes-core/musl/musl_%.bbappend
./sources/poky/meta/recipes-core/musl/musl_git.bb
./sources/poky/meta/recipes-core/musl/musl-utils.bb

**Comment by kraj** [comment]
interesting, Is there some other layer or config metadata which is blacklisting musl or `BBMASK`'ing it ?

**Comment by kraj** [comment]
thud is EOL
