### ISSUE TITLE
libunwind dependency get replaced with llvm-libunwind

### ISSUE THREAD

**Issue by saininav** [kraj/meta-clang#200]
meta-clang layer is added in bblayer in order to compile opencl recipes from meta-intel.

While build igt-gpu-tools recipe from meta-intel, throw configuration error:

checking whether make supports nested variables... (cached) yes
checking for libdrm >= 2.4.82... yes
checking for pciaccess >= 0.10... yes
checking for libkmod... yes
checking for libprocps... yes
checking for libunwind... no
configure: error: Package requirements (libunwind) were not met:

No package 'libunwind' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables LIBUNWIND_CFLAGS
and LIBUNWIND_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

While debugging with '$ bitbake igt-gpu-tool -e ' found that libunwind get replaced with llvm-libunwind.

**Comment by saininav** [comment]
> if you dont want to use llvm-libunwind, in recipe please set
> 
> ```
> UNWINDLIB = ""
> ```

I created a patch, which solved my issue:
https://github.com/saininav/meta-clang/commit/8cd463bfbadfc07d692c33eeaff79984996cdee1

**Comment by saininav** [comment]
Provide your feedback on https://github.com/saininav/meta-clang/commit/8cd463bfbadfc07d692c33eeaff79984996cdee1 patch

**Comment by saininav** [comment]
Hi Khem,

On using UNWINDLIB = "" in my recipe. Throw below error:

ERROR: igt-gpu-tools-1.24-r0 do_prepare_recipe_sysroot: The file /usr/include/unwind.h is installed by both llvm-libunwind and libunwind, aborting

Do I need to set PREFERRED_PROVIDER ?

**Comment by kraj** [comment]
I think it should be UNWINDLIB = “—unwindlib=libgcc”

**Comment by saininav** [comment]
Still issue remains...

**Comment by kraj** [comment]
please try with https://github.com/kraj/meta-clang/pull/204

**Comment by saininav** [comment]
Build Pass. Thanks Khem. I will give a try on other opencl (clang) recipes too.

**Comment by kraj** [comment]
Should be fixed now
