### ISSUE TITLE
TUNE_CCARGS breaks SSTATE checksums

### ISSUE THREAD

**Issue by mythi** [kraj/meta-clang#24]
I'm using an SSTATE_MIRROR to get clang pre-built by our CI build system but I noticed my build target always re-builds clang locally and sstate is invalid.

With bitbake-diffsigs I get that TUNE_CCARGS changes the hash. More specifically, the `-I${PKG_CONFIG_SYSROOT_DIR}${includedir}/libxml2` makes it build specific.

**Comment by mythi** [comment]
using krogoth / 3.8. Just saw bf0a01851fb7cd8d66a23cef0f69df519c085eff.

**Comment by kraj** [comment]
@mythi that patch is good for clang 3.9, however it hasnt been tested with clang 3.8, IIRC it was needed with some older version of clang I dont remember if it was 3.8 or older. If you can test it out and report back, I would be happy to cherry-pick it to krogoth

**Comment by mythi** [comment]
Fixed by #25
