### ISSUE TITLE
Native clang install targets x86-64 by default

### ISSUE THREAD

**Issue by hpux735** [kraj/meta-clang#26]
I'm trying to install a compiler on the target (an Armv7 system) that will compile native (Armv7) binaries.  To my top-level (image) recipe I added the `clang` dependency.  Build completes, and the target has a copy of clang that runs on arm.  However, the default triple of the compiler on the target is x86-64:

```
root@sav-001aae031ede0000:/# clang -v
clang version 3.7.0 (/home/wdillon/savant/build_tstat/downloads/git2/github.com.llvm-mirror.clang.git/ 75805b9d664254627)
Target: x86_64-unknown-linux-gnu
Thread model: posix
root@sav-001aae031ede0000:/# uname -a
Linux sav-001aae031ede0000 3.14.14+pro-8.1-504+g688b8af #1 SMP Mon Oct 10 14:44:01 UTC 2016 armv7l GNU/Linux
```

I've tried a few different variations on the clang recipe, including `clang-dev` and `clang-native` (clang-native doesn't work, but I don't know whether it's supposed to be used in this way).

It seems like clang is happy to be told to target `armv7-unknown-linux-gnueabihf` on the command line, but later on the workflow, I don't always control the invocation of clang (the end-goal is swift).  I haven't tested this completely; I just discovered this and have apparently omitted binutils.  (is there a recipe for gold that you know of)

Any ideas for how to correct the default triple?

Thanks!!

**Comment by kraj** [comment]
you can pass -target armv7l option on cmdline to clang
