### ISSUE TITLE
bpftrace building fails with Clang 10.0.0

### ISSUE THREAD

**Issue by Leo-Yan** [kraj/meta-clang#287]
**Describe the bug**
I also found the bpftrace building fails with Clang 10.0.0.  bpftrace added support Clang 9.0 a few days ago but has not supported Clang 10.0.0 yet.  So before bpftrace support Clang 10.0.0, please consider to add it into blacklist.

I will send a patch for OE building after bpftrace get ready for Clang 10.   

**To Reproduce**
add meta-clang into layer
bitbake bpftrace

**Comment by kraj** [comment]
Thank you @Leo-Yan

**Comment by kraj** [comment]
fails on musl as well
https://errors.yoctoproject.org/Errors/Details/392792/

**Comment by Leo-Yan** [comment]
> fails on musl as well
> https://errors.yoctoproject.org/Errors/Details/392792/

Have sent PR to mark musl incompatible: https://github.com/kraj/meta-clang/pull/292.

**Comment by Leo-Yan** [comment]
I have verified the latest meta-clang, bpftrace can build successfully with Clang 10.  So can we close this ticket?

P.s. I was committing patch to update git commit for bpftrace but recognized @ovpanait has committed patch, thanks for the patches!

**Comment by kraj** [comment]
Sure go ahead
