### ISSUE TITLE
I would like to control which LLVM projects to compile

### ISSUE THREAD

**Issue by Lorac** [kraj/meta-clang#316]
**Is your feature request related to a problem? Please describe.**
At the moment when using clang, there is no way to opt-out of the clang-extra-tools, lld or lldb. They are built no matter what. To reduce build time, package size, do you know a way to let the user control which projects to install? I think the current default is too big and takes too much time.

https://github.com/kraj/meta-clang/blob/46db90bf7ac1d7ab1078770423317071154c495c/recipes-devtools/clang/clang_git.bb#L117

**Describe the solution you'd like**
I would like to have the control over which project is built with a variable maybe? `LLVM_ENABLE_PROJECTS=...`

**Describe alternatives you've considered**
I could do a bbappend in my own layer modifying `EXTRA_OECMAKE`

**Comment by kraj** [comment]
covert them to packageconfigs but it will need some careful crafting
