### ISSUE TITLE
dunfell branch

### ISSUE THREAD

**Issue by priv-kweihmann** [kraj/meta-clang#336]
After master and dunfell already starting to diverge (at least for poky and meta-oe) it would be nice to have a dedicated branch for dunfell here as well

**Comment by kraj** [comment]
@priv-kweihmann good suggestion. I was thinking for waiting till 10.0.1 is out. Which should be only a week or so.

**Comment by priv-kweihmann** [comment]
@kraj any news? In combination with the busybox append (ee1dcdfbb8d31f168b26c2e3e5be97efea6537df) the layer currently breaks a lot of builds for me - so any relief is highly appreciated.

**Comment by kraj** [comment]
yeah unfortunately 10.0.1 went into rc4 and is still not done. I think I will branch now and do a merge when that happens into dunfell.

**Comment by priv-kweihmann** [comment]
Thanks

**Comment by kraj** [comment]
dunfell branch is available now

**Comment by priv-kweihmann** [comment]
Thanks a lot - could you then also remove the busybox append in master?

**Comment by kraj** [comment]
> Thanks a lot - could you then also remove the busybox append in master?

it cant be removed but needed porting which I have already proposed here
https://github.com/kraj/meta-clang/pull/345
