### ISSUE TITLE
meta-environment: create_sdk_files should not be run if clang is not included in the SDK (CLANGSDK=0 default)

### ISSUE THREAD

**Issue by rmi1974** [kraj/meta-clang#338]
Split out from https://github.com/kraj/meta-clang/issues/335

If clang is not included in the SDK (CLANGSDK=0 default), https://github.com/kraj/meta-clang/blob/master/recipes-core/meta/meta-environment.bbappend will unconditionally append export CLANGxxx=yyy. This results in variables that refer to non-existing tools. It could be made conditional.

**Comment by kraj** [comment]
this should be fixed now, please try latest master and reopen if more work is needed.
