### ISSUE TITLE
bcc does not compile with clang 11

### ISSUE THREAD

**Issue by kraj** [kraj/meta-clang#348]
**Describe the bug**
When using yoe/mut branch which has clang 11 ( pre-release ) bcc does not compile and ends up with this error
https://errors.yoctoproject.org/Errors/Details/424083/

**To Reproduce**

Use yoedistro fork of meta-clang and yoe/mut branch
https://github.com/YoeDistro/meta-clang/tree/yoe/mut

**Expected behavior**
It should build/compile successfully

**Comment by kraj** [comment]
FYI @realhezhe

**Comment by kraj** [comment]
@ovpanait can you take a look ?

**Comment by ovpanait** [comment]
Sure, I will take a look. I think it can be solved via an upgrade to v0.14+.
