### ISSUE TITLE
error: unknown target CPU 'cortex-a72.cortex-a53'

### ISSUE THREAD

**Issue by ambrice** [kraj/meta-clang#415]
Related to issue #313, on gatesgarth branch in poky, -mtune=cortex-a72.cortex-a53 has been changed to -mcpu=cortex-a72.cortexx-a53.  Causing chromium to fail to build with:

    error: unknown target CPU 'cortex-a72.cortex-a53'

The current fix in clang.bbclass causes both -mcpu=cortex-a72.cortex-a53 and -mtune=cortex-a53 to be set, though -mtune was not set previously.

**Comment by kraj** [comment]
@ambrice can you test the proposed patch on gatesgarth and report back?

**Comment by kraj** [comment]
the patch has landed for master, it needs to be backported to release branches then open backport requests
