### ISSUE TITLE
Support for Clang Static Analysis

### ISSUE THREAD

**Issue by romanek-adam** [kraj/meta-clang#44]
Hi Khem!

I'd like to ask about the status of support for Clang Static Analyzer.

I see there's scan-build.bbclass with just one variable - SCANBUILD. I couldn't find any code which would handle it. Am I missing something?

I also found a [thread](https://lists.yoctoproject.org/pipermail/yocto/2015-August/026300.html) on the Yocto mailing list. What is the progress so far?

I'd be glad to contribute if possible, I only need to know where we are and what are the next steps...

Regards,
Adam

**Comment by kraj** [comment]
its on my list of things to do. All contributions are welcome !!

**Comment by kraj** [comment]
This should be available now.
