### ISSUE TITLE
It's not possible to use LTO

### ISSUE THREAD

**Issue by zavorka** [kraj/meta-clang#45]
Adding `-flto=thin -fuse-ld=gold` to the `CCARGS` variable causes linking errors. Have anyone even tried using LTO with yocto?

**Comment by kraj** [comment]
@zavorka I havent used it distro wide, but on some packages I have used thin-lto. lto works ok on yocto with gcc and I thought it works well with clang as well. Can you describe the issue you are seeing.

**Comment by zavorka** [comment]
@kraj Well, the first problem is that the `clang-cross-arm` recipe won't produce `LLVMgold.so` but that's easily fixed by appending `-DLLVM_BINUTILS_INCDIR=${includedir}` to the `EXTRA_OECMAKE` variable.

Then I put the `flto=thin -fuse-ld=gold` parameters into `TUNE_CCARGS` and substitute `ar`, `nm` and `ranlib` for their `llvm-` prefixed counterparts. Unfortunately, the `gold` linker produced by `binutils-cross-arm` can't handle the `armelf_linux_eabi` emulation (according to the error messages I get flooded with). Funnily enough, if I try copying the `ld.gold` binary from `binutils-native` into the `recipe-sysroot`, unsupported emulation problem is gone, though immediately replaced by `gold`'s inability to read the bitcode (which doesn't make sense -- it loads the `LLVMgold.so` plugin just ok).

Finally, I've got `musl` built with ThinLTO once I replaced `gold` for `lld`. Sadly, there's no `lld-cross-arm` recipe yet, so there's a non-trivial amount of work yet to be done.

**Comment by kraj** [comment]
@zavorka thanks for trying it out. There are bunch of issues you are seeing

please submit a patch for clang-cross-arm to this layer
Also add a new issue to add lld-cross 

binutils-cross gold issue needs investigation this looks like OE bug to me.

**Comment by kraj** [comment]
@zavorka now lld is available in cross toolchain adding `-fuse-ld=lld` should be able to use it. Can you try your experiment with latest meta-clang ?

**Comment by kraj** [comment]
https://github.com/kraj/meta-clang/commit/00b9cd93d591099071e7087b9a354da6338dc1b7

lets clang itself build with Thin LTO, so I am interested to know if it will work for other recipes

**Comment by kraj** [comment]
https://github.com/kraj/meta-clang/pull/96

should help with this issue can you verify with latest master ?

**Comment by kraj** [comment]
@zavorka can you try latest master, -fuse-ld=lld should behave better hopefully.

**Comment by kraj** [comment]
LTO work and -fuse-ld=lld works too in SDK environment as well as internal builds.

**Comment by anilavakundu** [comment]
@zavorka  I was hoping if you could tell me which EXTRA_OECMAKE did you change LLVMgold.so isn't built for me either
