### ISSUE TITLE
clang-native compilation error Assembler mesages 

### ISSUE THREAD

**Issue by roystonvasey** [kraj/meta-clang#527]
clang-native do_compile fails with error messages:

{standard input}: Assembler messages:
{standard input}:46751: Warning: end of file not at end of a line; newline inserted
{standard input}:47221: Error: bad register name `%rd'
{standard input}: Error: open CFI at the end of file; missing .cfi_endproc directive
g++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
The host build platform is x86_64-linux.
Using meta-clang master pulled yesterday.

**Comment by kraj** [comment]
@roystonvasey your build machine is running out of memory, perhaps you need a better spec'ed machine with atleast 16GB of RAM

**Comment by roystonvasey** [comment]
Many thanks your suggestion worked.
