### ISSUE TITLE
Yocto 3.1.13 missing recipes - dunfell-clang12

### ISSUE THREAD

**Issue by jwinarske** [kraj/meta-clang#561]
**Describe the bug**
Branch: dunfell-clang12
Yocto: 3.1.13

```
ERROR: No recipes available for:
[363](https://github.com/meta-flutter/meta-flutter/runs/5055075725?check_suite_focus=true#step:7:363)
  /__w/meta-flutter/yocto-dunfell/meta-clang/recipes-multimedia/mediasdk/intel-mediasdk_%.bbappend
[364](https://github.com/meta-flutter/meta-flutter/runs/5055075725?check_suite_focus=true#step:7:364)
  /__w/meta-flutter/yocto-dunfell/meta-clang/recipes-security/optee/optee-os-stm32mp_%.bbappend
[365](https://github.com/meta-flutter/meta-flutter/runs/5055075725?check_suite_focus=true#step:7:365)
```

Workaround:
          rm -rf meta-clang/recipes-multimedia/mediasdk/intel-mediasdk_%.bbappend
          rm -rf meta-clang/recipes-security/optee/optee-os-stm32mp_%.bbappend

**Comment by kraj** [comment]
https://github.com/kraj/meta-clang/commit/92abd44335b84fc895ddc166694fe8b2a2783ae6 should fix it, please try latest branch

**Comment by jwinarske** [comment]
@kraj Builds are in flight.  Should know more after lunch.  Thanks!

**Comment by jwinarske** [comment]
@kraj Two builds down.  So far so good

**Comment by jwinarske** [comment]
@kraj all prior failures have been accounted for.  Fix is good.  Thanks again.
