### ISSUE TITLE
clang.bbclass: Handle big.LITTLE mtune options on arm/aarch64

### ISSUE THREAD

**Issue by yangpeng1995** [kraj/meta-clang#576]
Hi @kraj ,
There may be some problems with this submission.
https://github.com/kraj/meta-clang/commit/46db90bf7ac1d7ab1078770423317071154c495c
line 35:
TUNE_CCARGS_append_toolchain-clang = "${@bb.utils.contains_any("TUNE_FEATURES", "cortexa75-cortex-a55 cortexa76-cortex-a55", " -mtune=cortex-a55", "", d)}"

I refer to default configuration of Yocto/Poky for cortexa76-cortexa55: 
https://git.yoctoproject.org/poky/tree/meta/conf/machine/include/arm/armv8-2a/tune-cortexa76-cortexa55.inc

I think "cortexa75-cortex-a55 cortexa76-cortex-a55" should modified to "cortexa75-cortexa55 cortexa76-cortexa55".
When I applying the cortexa76-cortex-A55 configuration in Yocto/Poky, then use Clang to compile some recipes. I noticed this minor error.

**Comment by kraj** [comment]
@yangpeng1995 yes you are right its a typo. Would you mind submitting a patch ?

**Comment by yangpeng1995** [comment]
Of course, I'd be happy to submit a patch to fix this minor problem.

**Comment by yangpeng1995** [comment]
submitting a patch.
https://github.com/kraj/meta-clang/pull/577
