### ISSUE TITLE
PackageConfig for dynamic libraries

### ISSUE THREAD

**Issue by mdavis777** [kraj/meta-clang#58]
Is it possible to make the dynamic libraries portion of the target class (-DLLVM_BUILD_LLVM_DYLIB=ON -DLLVM_LINK_LLVM_DYLIB=ON) a packageconfig?

They are causing issues when I try to use clang with stdlibc++ and especially libgcc_s.  Specifically I am getting a lot of "commandline error option registered more than once".

Something along the lines of [this](https://github.com/mdavis777/meta-clang/commit/138ab822c54cfd8c888845f0cee19622c489e602)

Or if you prefer I the opposite way where static-libs is the packageconfig and it is disabled by default

**Comment by kraj** [comment]
@mdavis777 please prose this patch as a pr, I think using packageconfig is a good thing and reversing the logic is not required so patch as such seems ok to me.

**Comment by mdavis777** [comment]
Add pull request #60
