### ISSUE TITLE
collect2: fatal error: ld terminated with signal 9 [Killed]

### ISSUE THREAD

**Issue by walkthetalk** [kraj/meta-clang#6]
looks like the memory (8GB) is not enough.

4 parallel ld running, everyone use ~2G memory.

so maybe we should use single thread to make clang?
PARALLEL_MAKE = ""

**Comment by kraj** [comment]
Its possible, however one machine which has 8Gb built is fine before 3.8 upgrade. I havent tried it
since then. All my machines have 16Gb. You can select PARALLEL_MAKE_pn-clang-native = ""

in your local.conf. we should not punish the boxes which have good configs.
