### ISSUE TITLE
[CRITICAL] new clang-native.bbclass in incorrect folder

### ISSUE THREAD

**Issue by bmx666** [kraj/meta-clang#651]
build failed due to this commit -> https://github.com/kraj/meta-clang/commit/d89de99cbbb171a21f37ce64dd9ec2ef79fa033a
because **clang-native.bbclass** MUST BE located in **classes** folder, not in **classes-recipe**

**Comment by kraj** [comment]
are you on latest `master` branch of bitbake/poky ? if not please update retry and report back.

**Comment by bmx666** [comment]
Hi @kraj thanks for quick update, sorry for that.
But now our servers build NXP and BoundaryDevices which pointed somehow on meta-clang "master" in all branches, seems they all affected now... Like example
https://github.com/boundarydevices/boundary-bsp-platform/blob/kirkstone/default.xml

**Comment by kraj** [comment]
> Hi @kraj thanks for quick update, sorry for that. But now our servers build NXP and BoundaryDevices that points on **meta-clang** "master" in all branches, seems they all affected now... Like example https://github.com/boundarydevices/boundary-bsp-platform/blob/kirkstone/default.xml

hmm you are mixing kirkstone and master but I guess keeping this in classes/ is a good workaround for now. I will push such a change into meta-clang master for now.
