### ISSUE TITLE
When installing nativesdk-clang-tools, for a sdk, it installs clang compiler

### ISSUE THREAD

**Issue by Lorac** [kraj/meta-clang#676]
**Describe the bug**
Given that I only want the clang tooling but not the compiler. If I decide to install `nativesdk-clang-tools` it will install clang compiler which isn't what I wanted to install.

**To Reproduce**
Add `nativesdk-clang-tools` to TOOLCHAIN_HOST_TASK

**Expected behavior**
Only install `nativesdk-clang-tools` binaries and the needed .so, but not the compiler and its headers, intrinsic, etc.

**Desktop (please complete the following information):**
 - OS: Linux, Debian 11

**Comment by kraj** [comment]
its interesting who is pulling nativesdk-clang. Can you look into output of `bitbake -g nativesdk-clang-tools` or post the output here as well.

**Comment by Lorac** [comment]
nativesdk-clang-tools is a package and can't be used to do that on kirkstone. I think you mean `bitbake -g nativesdk-clang` ?

**Comment by Lorac** [comment]
I know that mesa depends on clang. But it doesn't RDEPENDS, maybe the way mesa depends on clang is incorrect?

**Comment by kraj** [comment]
Well may be add -g to sdk target build

**Comment by Lorac** [comment]
task-depends.dot of the -g sdk target build: https://file.io/qFVjQv9bSvNX

**Comment by kraj** [comment]
who is pulling `nativesdk-clang-glue` I think thats what is pulling it in.

**Comment by Lorac** [comment]
`clang-crosssdk-x86_64.do_prepare_recipe_sysroot` is needed to create nativesdk-clang-glue

**Comment by Lorac** [comment]
@kraj do you have any updates on this?

**Comment by kraj** [comment]
I finally found some time to look into it and I see

```
% readelf -d clang-apply-replacements

Dynamic section at offset 0x1dd08 contains 32 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libclang-cpp.so.16]
 0x0000000000000001 (NEEDED)             Shared library: [libLLVM-16.so]

```

Which means the tools depend on llvm and clang library. Which will be pulled in as dependency and it will automatically pull in `nativesdk-clang-libclang-cpp` and `nativesdk-clang-libllvm`
