### ISSUE TITLE
clang-15: error: linker command failed while building chromium package in yocto Krikstone

### ISSUE THREAD

**Issue by Ravikasyap** [kraj/meta-clang#710]
**Describe the bug**
Trying to build chromium-ozone-wayland using bitbake command and getting attached error.  Using meta-browser,openembeeded-core and meta-clang to build the chromium. 
 
**To Reproduce**
1. add layer https://github.com/OSSystems/meta-browser.git 
2. add layer meta-brower and meta-clang in bblayer file
3. build the package like bitbake chromium-ozone-wayland
4. See error :
 | DEBUG: Executing shell function do_compile
| [1/267] python3 ../../tools/generate_shim_headers/generate_shim_headers.py --generate --headers-root /home/jofrartc/var-fslc-yocto/build_xwayland/tmp/work/armv8a-mx8mm-fslc-linux/chromium-ozone-wayland/106.0.5249.119-r0/chromium-106.0.5249.119/third_party/flac/include --output-directory /home/jofrartc/var-fslc-yocto/build_xwayland/tmp/work/armv8a-mx8mm-fslc-linux/chromium-ozone-wayland/106.0.5249.119-r0/chromium-106.0.5249.119/out/Release/gen/shim_headers/flac_shim FLAC/all.h FLAC/assert.h FLAC/callback.h FLAC/export.h FLAC/format.h FLAC/metadata.h FLAC/ordinals.h FLAC/stream_decoder.h FLAC/stream_encoder.h
| [2/2] python3 "../../build/toolchain/gcc_link_wrapper.py" --output="./chrome" -- aarch64-fslc-linux-clang++ -target aarch64-fslc-linux  -march=armv8-a+crc+crypto -mlittle-endian -Qunused-arguments -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security --sysroot=/home/jofrartc/var-fslc-yocto/build_xwayland/tmp/work/armv8a-mx8mm-fslc-linux/chromium-ozone-wayland/106.0.5249.119-r0/recipe-sysroot -Wl,--version-script=../../build/linux/chrome.map -fuse-ld=lld -Wl,--fatal-warnings -Wl,--build-id=sha1 -fPIC -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -Wl,--icf=all -Wl,--color-diagnostics -Wl,-mllvm,-instcombine-lower-dbg-declare=0 -flto=thin -Wl,--thinlto-jobs=4 -Wl,--thinlto-cache-dir=thinlto-cache -Wl,--thinlto-cache-policy=cache_size=10\%:cache_size_bytes=40g:cache_size_files=100000 -Wl,-mllvm,-import-instr-limit=30 -fwhole-program-vtables -Wl,--no-call-graph-profile-sort -Wl,-O2 -Wl,--gc-sections -rdynamic -Wl,-z,defs -Wl,--as-needed -pie -Wl,--disable-new-dtags -Wl,--lto-O2 -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -fmacro-prefix-map=/home/jofrartc/var-fslc-yocto/build_xwayland/tmp/work/armv8a-mx8mm-fslc-linux/chromium-ozone-wayland/106.0.5249.119-r0=/usr/src/debug/chromium-ozone-wayland/106.0.5249.119-r0                      -fdebug-prefix-map=/home/jofrartc/var-fslc-yocto/build_xwayland/tmp/work/armv8a-mx8mm-fslc-linux/chromium-ozone-wayland/106.0.5249.119-r0=/usr/src/debug/chromium-ozone-wayland/106.0.5249.119-r0                      -fdebug-prefix-map=/home/jofrartc/var-fslc-yocto/build_xwayland/tmp/work/armv8a-mx8mm-fslc-linux/chromium-ozone-wayland/106.0.5249.119-r0/recipe-sysroot=                      -fdebug-prefix-map=/home/jofrartc/var-fslc-yocto/build_xwayland/tmp/work/armv8a-mx8mm-fslc-linux/chromium-ozone-wayland/106.0.5249.119-r0/recipe-sysroot-native=  -Wl,-z,relro,-z,now  -stdlib=libc++ -o "./chrome" -Wl,--start-group @"./chrome.rsp"  -Wl,--end-group  -latomic -ldl -lpthread -lrt -lgmodule-2.0 -lgobject-2.0 -lgthread-2.0 -lglib-2.0 -lsmime3 -lnss3 -lsoftokn3 -lnssutil3 -lplds4 -lplc4 -lnspr4 -latk-1.0 -latk-bridge-2.0 -lgio-2.0 -ldbus-1 -lresolv -ljpeg -lexpat -luuid -ldrm -lxkbcommon -lm -lwayland-client -lwayland-server -lgbm -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -lcairo -lasound -lpci -lz -latspi -lFLAC -lxslt -lxml2
| FAILED: chrome
| python3 "../../build/toolchain/gcc_link_wrapper.py" --output="./chrome" -- aarch64-fslc-linux-clang++ -target aarch64-fslc-linux  -march=armv8-a+crc+crypto -mlittle-endian -Qunused-arguments -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security --sysroot=/home/jofrartc/var-fslc-yocto/build_xwayland/tmp/work/armv8a-mx8mm-fslc-linux/chromium-ozone-wayland/106.0.5249.119-r0/recipe-sysroot -Wl,--version-script=../../build/linux/chrome.map -fuse-ld=lld -Wl,--fatal-warnings -Wl,--build-id=sha1 -fPIC -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -Wl,--icf=all -Wl,--color-diagnostics -Wl,-mllvm,-instcombine-lower-dbg-declare=0 -flto=thin -Wl,--thinlto-jobs=4 -Wl,--thinlto-cache-dir=thinlto-cache -Wl,--thinlto-cache-policy=cache_size=10\%:cache_size_bytes=40g:cache_size_files=100000 -Wl,-mllvm,-import-instr-limit=30 -fwhole-program-vtables -Wl,--no-call-graph-profile-sort -Wl,-O2 -Wl,--gc-sections -rdynamic -Wl,-z,defs -Wl,--as-needed -pie -Wl,--disable-new-dtags -Wl,--lto-O2 -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -fmacro-prefix-map=/home/jofrartc/var-fslc-yocto/build_xwayland/tmp/work/armv8a-mx8mm-fslc-linux/chromium-ozone-wayland/106.0.5249.119-r0=/usr/src/debug/chromium-ozone-wayland/106.0.5249.119-r0                      -fdebug-prefix-map=/home/jofrartc/var-fslc-yocto/build_xwayland/tmp/work/armv8a-mx8mm-fslc-linux/chromium-ozone-wayland/106.0.5249.119-r0=/usr/src/debug/chromium-ozone-wayland/106.0.5249.119-r0                      -fdebug-prefix-map=/home/jofrartc/var-fslc-yocto/build_xwayland/tmp/work/armv8a-mx8mm-fslc-linux/chromium-ozone-wayland/106.0.5249.119-r0/recipe-sysroot=                      -fdebug-prefix-map=/home/jofrartc/var-fslc-yocto/build_xwayland/tmp/work/armv8a-mx8mm-fslc-linux/chromium-ozone-wayland/106.0.5249.119-r0/recipe-sysroot-native=  -Wl,-z,relro,-z,now  -stdlib=libc++ -o "./chrome" -Wl,--start-group @"./chrome.rsp"  -Wl,--end-group  -latomic -ldl -lpthread -lrt -lgmodule-2.0 -lgobject-2.0 -lgthread-2.0 -lglib-2.0 -lsmime3 -lnss3 -lsoftokn3 -lnssutil3 -lplds4 -lplc4 -lnspr4 -latk-1.0 -latk-bridge-2.0 -lgio-2.0 -ldbus-1 -lresolv -ljpeg -lexpat -luuid -ldrm -lxkbcommon -lm -lwayland-client -lwayland-server -lgbm -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -lcairo -lasound -lpci -lz -latspi -lFLAC -lxslt -lxml2
| aarch64-fslc-linux-ld.lld: error: undefined symbol: gl::NativeViewGLSurfaceEGL::NativeViewGLSurfaceEGL(gl::GLDisplayEGL*, void*, std::__1::unique_ptr<gfx::VSyncProvider, std::__1::default_delete<gfx::VSyncProvider>>)
| >>> referenced by gl_surface_wayland.cc:35 (./../../ui/ozone/platform/wayland/gpu/gl_surface_wayland.cc:35)
| >>>               thinlto-cache/llvmcache-9639491A953CD564146775AB0EC2AB12145F93C3:(ui::GLSurfaceWayland::GLSurfaceWayland(gl::GLDisplayEGL*, std::__1::unique_ptr<wl_egl_window, ui::EGLWindowDeleter>, ui::WaylandWindow*))
| clang-15: error: linker command failed with exit code 1 (use -v to see invocation)
| ninja: build stopped: subcommand failed.
| WARNING: exit code 1 from a shell command.
ERROR: Task (/home/jofrartc/var-fslc-yocto/sources/meta-browser/meta-chromium/recipes-browser/chromium/chromium-ozone-wayland_106.0.5249.119.bb:do_compile) failed with exit code '1'

**Desktop (please complete the following information):**
 - OS:  : Ubuntu 
 - Version : 18.04 or 20.04

**Comment by kraj** [comment]
its not related to clang, but rather graphics driver provided for imx platforms, please report this issue to meta-browser or meta-freescale.
