### ISSUE TITLE
CLANG 16 breaks IGC in meta-intel

### ISSUE THREAD

**Issue by zboszor** [kraj/meta-clang#769]
**Describe the bug**

meta-clang master has just upgraded to CLANG 16.0.0, Yocto 4.2 Mickledore has LLVM 15.0.7

IGC and Compute Runtime are not yet ported to LLVM 16 and it seems that the standalone LLVM project from OE-Core is not available to build IGC with when using meta-clang.

**To Reproduce**

Use both meta-clang and meta-intel. Try to compile intel-graphics-compiler.

**Expected behavior**

IGC and Compute Runtime should build and work.

Please, branch off mickledore ASAP from the point just before upgrading to clang 16.

**Comment by kraj** [comment]
branch is created closing.
