### ISSUE TITLE
Request for nanbield branch variant with LLVM 15.x

### ISSUE THREAD

**Issue by zboszor** [kraj/meta-clang#869]
**Is your feature request related to a problem? Please describe.**

meta-clang master and meta-intel master/nanbield when used together fails to build intel-graphics-compiler because [IGC does not yet support anything past LLVM 15.x](https://github.com/intel/intel-graphics-compiler/projects/5).

As such, GPU acceleration must be disabled in oneDNN, and the whole Intel Compute Runtime must be left out.

**Describe the solution you'd like**

I will need a meta-clang nanbield branch variant that carries CLANG/LLVM 15.x latest point release so meta-intel can be used together.

**Describe alternatives you've considered**

I considered removing/replacing the Intel Compute Runtime (OpenCL driver) but Mesa Rusticl is not a viable alternative yet to support either SYCL or OpenCL backend for oneDNN.

**Additional context**

**Comment by kraj** [comment]
I am open for reviewing and accepting patches if someone works on it. Personally I do not have time or interest in supporting older clang on newer OE releases.

**Comment by anujm1** [comment]
I think just adding nanbield to LAYERSERIES_COMPAT for mickledore branch is enough. I tried it and it compiles fine with oe-core, meta-intel, meta-oe, meta-python in bblayers.conf. If that is preferred over having a separate branch, I can send that change.

**Comment by kraj** [comment]
> I think just adding nanbield to LAYERSERIES_COMPAT for mickledore branch is enough. I tried it and it compiles fine with oe-core, meta-intel, meta-oe, meta-python in bblayers.conf. If that is preferred over having a separate branch, I can send that change.

that should be fine.

**Comment by saininav** [comment]
https://github.com/kraj/meta-clang/pull/892

**Comment by zboszor** [comment]
See https://github.com/kraj/meta-clang/pull/924#issuecomment-2175957813

I am working on adding CLANG 15.0.7 to meta-clang with a set of versioned recipe names: `clang15`, etc.

This, together with small changes in `meta-intel` allows building IGC, Compute Runtime and opencl-clang 15 with CLANG 15 and linked to libLLVM-15.

All the recipes already adapted to the latest (non-versioned) LLVM/CLANG recipes are built with that version.
