### ISSUE TITLE
tmp-glibc/work/x86_64-linux/clang-native/12.0.0-r0/temp/run.do_compile.2386788' failed with exit code 1

### ISSUE THREAD

**Issue by hyl1416134510** [kraj/meta-clang#889]
I got an error when I ran bitbake clang

tmp-glibc/work-shared/llvm-project-source-12.0.0-r0/git/lldb/source/Plugins/Process/Linux/NativeRegisterContextLinux_x86_64.cpp:296:34: error: use of deleted function ‘lldb_private::process_linux::NativeRegisterContextLinux::NativeRegisterContextLinux()’
       m_reg_info(), m_gpr_x86_64() {

I don't know how to solve him, this is my gcc version
"gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6 Ubuntu1 ~16.04.12)"
Could you give me some advice? Thank you very much

I uploaded 
tmp-glibc\work\x86_64-linux\clang-native\12.0.0-r0\temp\log.do_compile

**Comment by hyl1416134510** [comment]
[temp.zip](https://github.com/kraj/meta-clang/files/13645436/temp.zip)

**Comment by kraj** [comment]
I would suggest to use `dunfell-clang14` branch

**Comment by hyl1416134510** [comment]
When I use Dunfall-clang14, I get a similar error. I wonder if this is caused by my compiler version. Do you have the recommended ubuntu version and gcc version for compiling Dunfall-clang14 or Dunfall-clang12

Right now I'm using ubuntu16 gcc 5.4.0

**Comment by kraj** [comment]
yeah if possible swith to ubuntu 18.04 atleast.

**Comment by kraj** [comment]
I am guessing using ubuntu 18.04 solved the problem. if not please re-open.
